require_relative "song"
require_relative "list"

list = List.new

list.add_song(Song.new("Blame It On Me", "Barenaked Ladies", 234, "But here we are again And were looking at each other as if each other were to blame You think youre so smart but Ive seen you naked And Ill probably see you naked again Milli Vanilli told you to blame it on the rain But if you blame it on the rain tell me what can be gained so If all else fails you can blame it on me If all else fails you can blame it on me If all else fails you can blame it on me If all else fails blame it on me But if all else fails you can blame it on me"))
list.add_song(Song.new("Money Trees", "Kendrick Lamar", 386, "Me and my niggas tryna get it, ya bish Ya bish, ya bish Hit this house lick tell me is you with it, ya bish Ya bish, ya bish Home invasion was persuasive Was persuasive, was persuasive From nine to five I know its vacant, ya bish Ya bish, ya bish Dreams of living life like rappers do like rappers do, like rappers do Back when condom wrappers wasnt cool They wasnt cool, they wasnt cool I fucked Sherane then went to tell my bros Tell my bros, tell my bros Then Usher Raymond Let it Burn came on Let it Burn came on, Let it Burncame on Hot sauce all in our Top Ramen, ya bish Ya bish, ya bish Parked the car and then we start rhyming, ya bish Ya bish, ya bish The only thing we had to free our mind Free our mind, free our mind Then freeze that verse when we see dollar signs Dollar signs, dollar signs You looking like an easy come up, ya bish Ya bish, ya bish A silver spoon I know you come from, ya bish Ya bish, ya bish And thats a lifestyle that we never knew We never knew, we never knew Go at a reverend for the revenue It go Halle Berry or hallelujah Pick your poison tell me what you do Everybody gon  respect the shooter But the one in front of the gun lives forever The one in front of the gun lives forever And I been hustlin  all day, this a way, that a way Through canals and alleyways, just to say Money trees is the perfect place for shade and thats just how I feel now, now A dollar might just fuck your main bitch thats just how I feel now A dollar might say fuck them niggas that you came with thats just how I feel now, now A dollar might, just make that lane switch thats just how I feel now A dollar might, turn to a million and we all rich thats just how I feel"))
list.add_song(Song.new("Under Pressure", "David Bowie & Queen", 247, "Pressure pushing down on me Pressing down on you, no man ask for Under pressure that burns a building down Splits a family in two Puts people on streets Um ba ba be Um ba ba be De day da Ee day da, thats okay Its the terror of knowing what the world is about Watching some good friends screaming Let me out! Pray tomorrow gets me higher Pressure on people, people on streets"))

puts list.duration